hacktoberfest:
- changed-files:
  - any-glob-to-any-file: '**'

hack-documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

hack-code:
- changed-files:
  - any-glob-to-any-file: ['**/*.ts', '**/*.js', '**/*.html', '**/*.json']
