name: "Pull Request Labeler"
on:
  pull_request_target:
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Hacktoberfest label
        if: github.event_name == 'pull_request_target'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "Hacktoberfest"
